---
- hosts: database
  tasks:
    - name: add hostname to config
      lineinfile: 
        dest: /home/centos/hostname.conf
        regexp: ^Hostname=.*
        insertafter:  ^# Hostname=
        line:  Hostname={{ ansible_hostname }}

